# Generated by Django 5.0.6 on 2024-05-21 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_address_country_useraccount_addresses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='parent_category',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='product_item',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='variation_value',
        ),
        migrations.RemoveField(
            model_name='variationoption',
            name='variation',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.DeleteModel(
            name='ProductImages',
        ),
        migrations.DeleteModel(
            name='ProductItem',
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
        migrations.DeleteModel(
            name='VariationOption',
        ),
    ]
