# Generated by Django 5.0.6 on 2024-05-23 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.productcategory'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.productcategory'),
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
