# Generated by Django 5.0.6 on 2024-05-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_category_alter_variation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='product-images'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='image',
            field=models.ImageField(null=True, upload_to='product-item-images'),
        ),
        migrations.AlterField(
            model_name='variationoption',
            name='value',
            field=models.CharField(max_length=25),
        ),
        migrations.DeleteModel(
            name='ProductImages',
        ),
    ]
