# Generated by Django 5.0.6 on 2024-06-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productitem_out_of_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.IntegerField(null=True),
        ),
    ]
