# Generated by Django 5.0.6 on 2024-06-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_base_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='price',
            field=models.FloatField(),
        ),
    ]
