# Generated by Django 5.0.6 on 2024-06-18 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0007_alter_product_base_price_alter_productitem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productitem',
            old_name='variation_value',
            new_name='variation_values',
        ),
        migrations.AlterField(
            model_name='variation',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variations', to='categories.productcategory'),
        ),
    ]
