# Generated by Django 5.0.6 on 2024-06-21 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_variation_value_productitem_variation_values_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productitem',
            old_name='variation_values',
            new_name='variation_options',
        ),
    ]
