# Generated by Django 5.0.6 on 2024-06-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_variation_values_productitem_variation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='variation_options',
            field=models.ManyToManyField(blank=True, related_name='product_items', to='products.variationoption'),
        ),
    ]
