# Generated by Django 5.0.6 on 2024-06-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_productitem_variation_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
