# Generated by Django 5.0.6 on 2024-06-23 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0011_remove_variation_category_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variations', to='categories.productcategory'),
        ),
    ]
