# Generated by Django 5.0.6 on 2024-06-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_image_alter_productitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='product-images'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='image',
            field=models.ImageField(null=True, upload_to='product-item-images'),
        ),
    ]
